# -*- coding: utf-8 -*-
"""
Full standard JVM opcode table (JVM SE 21 spec, 0x00-0xC9).
Each entry: opcode -> (mnemonic, operand_kind)

operand_kind values:
  none            - no operands
  byte            - 1 signed byte
  short           - 1 signed 2-byte value (sipush)
  ubyte_cp        - 1 unsigned byte, constant pool index (ldc)
  ushort_cp       - 2 unsigned bytes, constant pool index
  local_ubyte     - 1 unsigned byte, local variable index
  iinc            - 1 unsigned byte local index + 1 signed byte const
  branch2         - 2 signed bytes, branch offset (relative)
  branch4         - 4 signed bytes, branch offset (relative)
  atype           - 1 unsigned byte, array type code (newarray)
  invokeinterface - 2 bytes cp index + 1 byte count + 1 byte zero
  invokedynamic   - 2 bytes cp index + 2 zero bytes
  multianewarray  - 2 bytes cp index + 1 byte dimensions
  tableswitch     - variable length
  lookupswitch    - variable length
  wide            - variable length, modifies next instruction
"""

OPCODES = {
    0x00: ("nop", "none"),
    0x01: ("aconst_null", "none"),
    0x02: ("iconst_m1", "none"),
    0x03: ("iconst_0", "none"),
    0x04: ("iconst_1", "none"),
    0x05: ("iconst_2", "none"),
    0x06: ("iconst_3", "none"),
    0x07: ("iconst_4", "none"),
    0x08: ("iconst_5", "none"),
    0x09: ("lconst_0", "none"),
    0x0a: ("lconst_1", "none"),
    0x0b: ("fconst_0", "none"),
    0x0c: ("fconst_1", "none"),
    0x0d: ("fconst_2", "none"),
    0x0e: ("dconst_0", "none"),
    0x0f: ("dconst_1", "none"),
    0x10: ("bipush", "byte"),
    0x11: ("sipush", "short"),
    0x12: ("ldc", "ubyte_cp"),
    0x13: ("ldc_w", "ushort_cp"),
    0x14: ("ldc2_w", "ushort_cp"),
    0x15: ("iload", "local_ubyte"),
    0x16: ("lload", "local_ubyte"),
    0x17: ("fload", "local_ubyte"),
    0x18: ("dload", "local_ubyte"),
    0x19: ("aload", "local_ubyte"),
    0x1a: ("iload_0", "none"),
    0x1b: ("iload_1", "none"),
    0x1c: ("iload_2", "none"),
    0x1d: ("iload_3", "none"),
    0x1e: ("lload_0", "none"),
    0x1f: ("lload_1", "none"),
    0x20: ("lload_2", "none"),
    0x21: ("lload_3", "none"),
    0x22: ("fload_0", "none"),
    0x23: ("fload_1", "none"),
    0x24: ("fload_2", "none"),
    0x25: ("fload_3", "none"),
    0x26: ("dload_0", "none"),
    0x27: ("dload_1", "none"),
    0x28: ("dload_2", "none"),
    0x29: ("dload_3", "none"),
    0x2a: ("aload_0", "none"),
    0x2b: ("aload_1", "none"),
    0x2c: ("aload_2", "none"),
    0x2d: ("aload_3", "none"),
    0x2e: ("iaload", "none"),
    0x2f: ("laload", "none"),
    0x30: ("faload", "none"),
    0x31: ("daload", "none"),
    0x32: ("aaload", "none"),
    0x33: ("baload", "none"),
    0x34: ("caload", "none"),
    0x35: ("saload", "none"),
    0x36: ("istore", "local_ubyte"),
    0x37: ("lstore", "local_ubyte"),
    0x38: ("fstore", "local_ubyte"),
    0x39: ("dstore", "local_ubyte"),
    0x3a: ("astore", "local_ubyte"),
    0x3b: ("istore_0", "none"),
    0x3c: ("istore_1", "none"),
    0x3d: ("istore_2", "none"),
    0x3e: ("istore_3", "none"),
    0x3f: ("lstore_0", "none"),
    0x40: ("lstore_1", "none"),
    0x41: ("lstore_2", "none"),
    0x42: ("lstore_3", "none"),
    0x43: ("fstore_0", "none"),
    0x44: ("fstore_1", "none"),
    0x45: ("fstore_2", "none"),
    0x46: ("fstore_3", "none"),
    0x47: ("dstore_0", "none"),
    0x48: ("dstore_1", "none"),
    0x49: ("dstore_2", "none"),
    0x4a: ("dstore_3", "none"),
    0x4b: ("astore_0", "none"),
    0x4c: ("astore_1", "none"),
    0x4d: ("astore_2", "none"),
    0x4e: ("astore_3", "none"),
    0x4f: ("iastore", "none"),
    0x50: ("lastore", "none"),
    0x51: ("fastore", "none"),
    0x52: ("dastore", "none"),
    0x53: ("aastore", "none"),
    0x54: ("bastore", "none"),
    0x55: ("castore", "none"),
    0x56: ("sastore", "none"),
    0x57: ("pop", "none"),
    0x58: ("pop2", "none"),
    0x59: ("dup", "none"),
    0x5a: ("dup_x1", "none"),
    0x5b: ("dup_x2", "none"),
    0x5c: ("dup2", "none"),
    0x5d: ("dup2_x1", "none"),
    0x5e: ("dup2_x2", "none"),
    0x5f: ("swap", "none"),
    0x60: ("iadd", "none"),
    0x61: ("ladd", "none"),
    0x62: ("fadd", "none"),
    0x63: ("dadd", "none"),
    0x64: ("isub", "none"),
    0x65: ("lsub", "none"),
    0x66: ("fsub", "none"),
    0x67: ("dsub", "none"),
    0x68: ("imul", "none"),
    0x69: ("lmul", "none"),
    0x6a: ("fmul", "none"),
    0x6b: ("dmul", "none"),
    0x6c: ("idiv", "none"),
    0x6d: ("ldiv", "none"),
    0x6e: ("fdiv", "none"),
    0x6f: ("ddiv", "none"),
    0x70: ("irem", "none"),
    0x71: ("lrem", "none"),
    0x72: ("frem", "none"),
    0x73: ("drem", "none"),
    0x74: ("ineg", "none"),
    0x75: ("lneg", "none"),
    0x76: ("fneg", "none"),
    0x77: ("dneg", "none"),
    0x78: ("ishl", "none"),
    0x79: ("lshl", "none"),
    0x7a: ("ishr", "none"),
    0x7b: ("lshr", "none"),
    0x7c: ("iushr", "none"),
    0x7d: ("lushr", "none"),
    0x7e: ("iand", "none"),
    0x7f: ("land", "none"),
    0x80: ("ior", "none"),
    0x81: ("lor", "none"),
    0x82: ("ixor", "none"),
    0x83: ("lxor", "none"),
    0x84: ("iinc", "iinc"),
    0x85: ("i2l", "none"),
    0x86: ("i2f", "none"),
    0x87: ("i2d", "none"),
    0x88: ("l2i", "none"),
    0x89: ("l2f", "none"),
    0x8a: ("l2d", "none"),
    0x8b: ("f2i", "none"),
    0x8c: ("f2l", "none"),
    0x8d: ("f2d", "none"),
    0x8e: ("d2i", "none"),
    0x8f: ("d2l", "none"),
    0x90: ("d2f", "none"),
    0x91: ("i2b", "none"),
    0x92: ("i2c", "none"),
    0x93: ("i2s", "none"),
    0x94: ("lcmp", "none"),
    0x95: ("fcmpl", "none"),
    0x96: ("fcmpg", "none"),
    0x97: ("dcmpl", "none"),
    0x98: ("dcmpg", "none"),
    0x99: ("ifeq", "branch2"),
    0x9a: ("ifne", "branch2"),
    0x9b: ("iflt", "branch2"),
    0x9c: ("ifge", "branch2"),
    0x9d: ("ifgt", "branch2"),
    0x9e: ("ifle", "branch2"),
    0x9f: ("if_icmpeq", "branch2"),
    0xa0: ("if_icmpne", "branch2"),
    0xa1: ("if_icmplt", "branch2"),
    0xa2: ("if_icmpge", "branch2"),
    0xa3: ("if_icmpgt", "branch2"),
    0xa4: ("if_icmple", "branch2"),
    0xa5: ("if_acmpeq", "branch2"),
    0xa6: ("if_acmpne", "branch2"),
    0xa7: ("goto", "branch2"),
    0xa8: ("jsr", "branch2"),
    0xa9: ("ret", "local_ubyte"),
    0xaa: ("tableswitch", "tableswitch"),
    0xab: ("lookupswitch", "lookupswitch"),
    0xac: ("ireturn", "none"),
    0xad: ("lreturn", "none"),
    0xae: ("freturn", "none"),
    0xaf: ("dreturn", "none"),
    0xb0: ("areturn", "none"),
    0xb1: ("return", "none"),
    0xb2: ("getstatic", "ushort_cp"),
    0xb3: ("putstatic", "ushort_cp"),
    0xb4: ("getfield", "ushort_cp"),
    0xb5: ("putfield", "ushort_cp"),
    0xb6: ("invokevirtual", "ushort_cp"),
    0xb7: ("invokespecial", "ushort_cp"),
    0xb8: ("invokestatic", "ushort_cp"),
    0xb9: ("invokeinterface", "invokeinterface"),
    0xba: ("invokedynamic", "invokedynamic"),
    0xbb: ("new", "ushort_cp"),
    0xbc: ("newarray", "atype"),
    0xbd: ("anewarray", "ushort_cp"),
    0xbe: ("arraylength", "none"),
    0xbf: ("athrow", "none"),
    0xc0: ("checkcast", "ushort_cp"),
    0xc1: ("instanceof", "ushort_cp"),
    0xc2: ("monitorenter", "none"),
    0xc3: ("monitorexit", "none"),
    0xc4: ("wide", "wide"),
    0xc5: ("multianewarray", "multianewarray"),
    0xc6: ("ifnull", "branch2"),
    0xc7: ("ifnonnull", "branch2"),
    0xc8: ("goto_w", "branch4"),
    0xc9: ("jsr_w", "branch4"),
}

NEWARRAY_TYPES = {
    4: "boolean", 5: "char", 6: "float", 7: "double",
    8: "byte", 9: "short", 10: "int", 11: "long",
}
