import { useState } from "react";
import { Check, ChevronRight, Sparkles } from "lucide-react";
import { useEngine } from "../state/engine";

/* Мастер первого запуска (по прямой просьбе пользователя) - показывается
   один раз при первом старте клиента, до основного интерфейса. EULA -
   полный текст на английском (см. LICENSE_EULA.txt в корне проекта -
   этот текст здесь ПРОДУБЛИРОВАН как константа, а не читается через IPC,
   чтобы не зависеть от файловой системы/гонок при самом первом экране
   приложения). Картинки - чистый SVG в палитре приложения (акцентный
   зелёный/тёмный фон), не растровые изображения - генератора картинок у
   агента нет, а нарисованный от руки SVG хотя бы РЕАЛЬНО отрисуется. */

const EULA_TEXT = `NANODECOMPILER — END-USER LICENSE AGREEMENT (EULA)

Software: NanoDecompiler
Author / Publisher: NanoDev
Contact / Updates channel: https://t.me/NanoDev_mc

PLEASE READ THIS AGREEMENT CAREFULLY BEFORE USING THE SOFTWARE. BY CLICKING
"I ACCEPT" OR BY INSTALLING, COPYING, OR OTHERWISE USING NANODECOMPILER
("THE SOFTWARE"), YOU AGREE TO BE BOUND BY THE TERMS OF THIS AGREEMENT. IF
YOU DO NOT AGREE TO THESE TERMS, DO NOT INSTALL OR USE THE SOFTWARE.

1. GRANT OF LICENSE
   NanoDev ("the Author") grants you a non-exclusive, non-transferable,
   revocable license to install and use the Software on your own devices,
   for personal or internal development purposes, subject to the terms of
   this Agreement.

2. PERMITTED USE
   You may use the Software to decompile and inspect Java bytecode
   (including but not limited to Minecraft server plugins) that you
   personally own, that you have written yourself, or that you otherwise
   have the legal right to decompile (for example under an applicable
   open-source license, or with the explicit permission of the copyright
   holder).

3. RESTRICTIONS
   You may NOT:
   a) use the Software to decompile, reverse-engineer, or redistribute
      copyrighted material that you do not have the right to access or
      modify;
   b) use output produced by the Software to infringe upon the
      intellectual property rights of any third party;
   c) use the Software for any unlawful purpose, including but not
      limited to circumventing license checks, DRM, or other technical
      protection measures without authorization;
   d) resell, sublicense, or redistribute the Software itself as your own
      product without the Author's written permission;
   e) misrepresent output generated by the Software as original,
      independently-authored source code without disclosing that it was
      produced by decompilation.

4. NO WARRANTY
   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
   NON-INFRINGEMENT. Decompiled output is generated automatically and may
   be incomplete, inaccurate, or fail to compile; the Author makes no
   guarantee as to its correctness or fitness for any purpose.

5. LIMITATION OF LIABILITY
   IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER
   LIABILITY ARISING FROM, OUT OF, OR IN CONNECTION WITH THE SOFTWARE OR
   THE USE OR OTHER DEALINGS IN THE SOFTWARE, INCLUDING BUT NOT LIMITED TO
   ANY MISUSE OF DECOMPILED OUTPUT BY THE USER.

6. THIRD-PARTY CONTENT
   The Software may process files (.jar archives) that you supply. The
   Author does not review, endorse, or take responsibility for the
   content of files you choose to process. You are solely responsible for
   ensuring you have the right to decompile any file you provide to the
   Software.

7. BETA STATUS
   The Software may be distributed in a "BETA" state. Beta versions may
   contain bugs, incomplete features, or produce inaccurate output, and
   may change or be discontinued at any time without notice.

8. UPDATES
   The Software may check for and offer to install updates. You may
   decline updates, though continuing to use an outdated version is done
   at your own risk. Update channel and support: t.me/NanoDev_mc

9. TERMINATION
   This license is effective until terminated. It will terminate
   automatically without notice if you fail to comply with any provision
   of this Agreement. Upon termination, you must cease all use of the
   Software and destroy all copies in your possession.

10. GOVERNING TERMS
    This Agreement constitutes the entire agreement between you and the
    Author concerning the Software and supersedes any prior agreements,
    whether written or oral, relating to its subject matter.

By clicking "I Accept", you acknowledge that you have read, understood,
and agree to be bound by the terms of this Agreement.

— NanoDev`;

function WelcomeArt() {
  return (
    <svg width="220" height="160" viewBox="0 0 220 160" fill="none" aria-hidden>
      <rect x="20" y="30" width="180" height="110" rx="10" fill="#12160f" stroke="#2a3324" strokeWidth="1.5" />
      <rect x="20" y="30" width="180" height="22" rx="10" fill="#181f14" />
      <circle cx="34" cy="41" r="3" fill="#3a4a30" />
      <circle cx="44" cy="41" r="3" fill="#3a4a30" />
      <circle cx="54" cy="41" r="3" fill="#3a4a30" />
      <path d="M40 78 60 96 40 114" stroke="#9bf246" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round" />
      <rect x="76" y="108" width="60" height="6" rx="3" fill="#eaf0ea" opacity=".85" />
      <rect x="76" y="90" width="88" height="6" rx="3" fill="#3a4a30" />
      <rect x="76" y="72" width="72" height="6" rx="3" fill="#3a4a30" />
      <path d="M150 44 165 44 165 59" stroke="#9bf246" strokeWidth="3" strokeLinecap="round" opacity=".6" />
    </svg>
  );
}

function ShieldArt() {
  return (
    <svg width="120" height="120" viewBox="0 0 120 120" fill="none" aria-hidden>
      <path
        d="M60 12 L100 26 V56 C100 82 84 100 60 108 C36 100 20 82 20 56 V26 Z"
        fill="#12160f"
        stroke="#9bf246"
        strokeWidth="2"
        opacity=".9"
      />
      <path d="M42 58 L54 70 L80 44" stroke="#9bf246" strokeWidth="5" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

function DoneArt() {
  return (
    <svg width="140" height="120" viewBox="0 0 140 120" fill="none" aria-hidden>
      <circle cx="70" cy="60" r="46" fill="#12160f" stroke="#9bf246" strokeWidth="2" />
      <path d="M48 62 L64 78 L94 42" stroke="#9bf246" strokeWidth="6" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

type Step = "welcome" | "eula" | "options" | "done";

export function SetupWizard() {
  const { completeSetup, settings, saveSettings } = useEngine();
  const [step, setStep] = useState<Step>("welcome");
  const [accepted, setAccepted] = useState(false);
  const [autoUpdateCheck, setAutoUpdateCheck] = useState(settings.autoUpdateCheck);
  const [legitimacyCheck, setLegitimacyCheck] = useState(settings.legitimacyCheck);

  const finish = () => {
    saveSettings({ ...settings, autoUpdateCheck, legitimacyCheck });
    completeSetup();
  };

  return (
    <div className="fixed inset-0 z-[100] grid place-items-center bg-bg">
      <div className="animate-rise flex w-[480px] flex-col overflow-hidden rounded-2xl border border-line bg-surface shadow-2xl shadow-black/50">
        <div className="flex flex-col items-center gap-5 px-8 py-9 text-center">
          {step === "welcome" && (
            <>
              <WelcomeArt />
              <div>
                <p className="text-[16px] font-semibold text-ink">Добро пожаловать в NanoDecompiler</p>
                <p className="mt-2 text-[12.5px] leading-relaxed text-dim">
                  Декомпилятор и деобфускатор для Bukkit/Spigot/Paper/BungeeCord/Velocity-плагинов. Разработка —
                  NanoDev.
                </p>
              </div>
              <button className="btn btn-acid h-9 w-full text-[12.5px]" onClick={() => setStep("eula")}>
                Далее
                <ChevronRight size={14} />
              </button>
            </>
          )}

          {step === "eula" && (
            <>
              <ShieldArt />
              <p className="text-[14.5px] font-semibold text-ink">Лицензионное соглашение</p>
              <div className="mono h-[220px] w-full overflow-y-auto rounded-lg border border-line bg-bg p-3 text-left text-[10.5px] leading-relaxed whitespace-pre-wrap text-dim">
                {EULA_TEXT}
              </div>
              <label className="flex w-full cursor-pointer items-center gap-2 text-left text-[12px] text-ink/90">
                <input
                  type="checkbox"
                  checked={accepted}
                  onChange={e => setAccepted(e.target.checked)}
                  className="size-4 accent-acid"
                />
                Я прочитал(а) и принимаю условия лицензионного соглашения
              </label>
              <button
                className={"btn btn-acid h-9 w-full text-[12.5px] " + (!accepted ? "pointer-events-none opacity-40" : "")}
                onClick={() => setStep("options")}
                disabled={!accepted}
              >
                Принять и продолжить
                <ChevronRight size={14} />
              </button>
            </>
          )}

          {step === "options" && (
            <>
              <Sparkles size={44} className="text-acid" />
              <p className="text-[14.5px] font-semibold text-ink">Пара настроек напоследок</p>
              <div className="w-full space-y-2 text-left">
                <label className="flex items-center justify-between rounded-lg border border-line bg-bg px-3.5 py-2.5">
                  <span className="text-[12px] text-ink/90">Проверять обновления автоматически</span>
                  <input
                    type="checkbox"
                    checked={autoUpdateCheck}
                    onChange={e => setAutoUpdateCheck(e.target.checked)}
                    className="size-4 accent-acid"
                  />
                </label>
                <label className="flex items-center justify-between rounded-lg border border-line bg-bg px-3.5 py-2.5">
                  <span className="text-[12px] text-ink/90">Проверка легитимности плагинов</span>
                  <input
                    type="checkbox"
                    checked={legitimacyCheck}
                    onChange={e => setLegitimacyCheck(e.target.checked)}
                    className="size-4 accent-acid"
                  />
                </label>
              </div>
              <p className="text-[10.5px] text-faint">Всё это можно изменить позже в настройках.</p>
              <button className="btn btn-acid h-9 w-full text-[12.5px]" onClick={() => setStep("done")}>
                Далее
                <ChevronRight size={14} />
              </button>
            </>
          )}

          {step === "done" && (
            <>
              <DoneArt />
              <p className="text-[14.5px] font-semibold text-ink">Всё готово</p>
              <p className="text-[12px] text-dim">
                Обновления и поддержка — <span className="text-acid">t.me/NanoDev_mc</span>
              </p>
              <button className="btn btn-acid h-9 w-full text-[12.5px]" onClick={finish}>
                <Check size={14} />
                Начать работу
              </button>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
