"""
articles_mod2.py - Module 2: Decompilation Theory & Control Flow Structuring (021 - 040)
"""

MODULE_NAME = "02_decompilation_theory"

ARTICLES = [
    {
        "file": "021_foundations_of_decompilation.md",
        "title": "Foundations of Decompilation: Historical Perspectives and Modern Pipelines",
        "num": "021",
        "content": """# Article 021: Foundations of Decompilation: Historical Perspectives and Modern Pipelines

## 1. Executive Summary & Theoretical Context
Decompilation is the process of reversing the compilation transformation: translating low-level machine code or bytecode back into high-level source code. Formally established by Cristina Cifuentes (1994), decompilation transforms an unstructured instruction stream with jump instructions into a structured Abstract Syntax Tree (AST).

## 2. The Classic 5-Stage Decompiler Pipeline
```
[Bytecode / ClassFile]
         │
         ▼ (1. Front-End Parsing)
[Instruction Stream & Exception Tables]
         │
         ▼ (2. Control Flow Analysis)
[Control Flow Graph (CFG) & Dominator Trees]
         │
         ▼ (3. Dataflow Analysis & SSA)
[High-Level Expressions & Type Recovery]
         │
         ▼ (4. AST Structuring)
[Hierarchical AST (If, Loop, Switch, Try)]
         │
         ▼ (5. Back-End Code Generation)
[High-Quality Java Source Code]
```

## 3. The Central Challenge: Information Loss
Compilation is lossy:
- High-level control structures (`while`, `for`, `switch`) are flattened into conditional jumps (`if_icmpne`, `goto`).
- Local variable scopes and names are discarded (unless debug tables are preserved).
- Expression boundaries are dissolved into temporary operand stack pushes/pops.
Decompilation algorithms must invert these lossy mappings using deterministic structural patterns and lattice-based dataflow analysis.

## 4. NanoDecompiler C++ Engine Integration
NanoDecompiler executes this exact pipeline across its core C++ modules:
- Front-end: `classfile.cpp`, `disassembler.cpp`.
- CFG & Structuring: `cfg.cpp`, `structure.cpp`.
- Dataflow & Stack: `stackvm.cpp`, `engine.cpp`.
- AST & Emitting: `ast_nodes.hpp`, `render_class.cpp`, `emit.cpp`.

## 5. References
- Cifuentes, C. *Reverse Compilation Techniques*. PhD Thesis, Queensland University of Technology, 1994.
- Muchnick, S. S. *Advanced Compiler Design and Implementation*. Morgan Kaufmann, 1997.
"""
    },
    {
        "file": "022_control_flow_graph_construction.md",
        "title": "Control Flow Graph Construction and Basic Block Identification",
        "num": "022",
        "content": """# Article 022: Control Flow Graph Construction and Basic Block Identification

## 1. Executive Summary & Specification
A Control Flow Graph (CFG) $G = (V, E)$ is a directed graph where vertices $V$ represent **Basic Blocks** (linear sequences of instructions with single entry and single exit) and directed edges $E$ represent possible transfers of control.

## 2. Basic Block Identification Algorithm
An instruction at offset $i$ is a **Leader** if:
1. $i = 0$ (the entry instruction of the method).
2. $i$ is the target of any conditional or unconditional jump (`goto`, `if*`, `tableswitch`, `lookupswitch`).
3. $i$ is the target of an exception handler (`handler_pc`).
4. $i$ immediately follows any jump, switch, return, or `athrow` instruction.

Each basic block spans from a leader up to (and including) the instruction immediately preceding the next leader or terminal jump.

## 3. Edge Categorization
- **Fallthrough Edge**: Natural sequential flow from block $B_i$ to $B_{i+1}$ (valid when $B_i$ does not end in unconditional jump/return).
- **Branch Edge (True/False)**: Generated by conditional jump opcodes (`ifeq`, `if_icmpeq`).
- **Switch Edges**: Multiple out-edges corresponding to case keys and the default target.
- **Exception Edges**: Implicit edges connecting any instruction inside a protected range $[start, end)$ to the corresponding `handler_pc`.

## 4. NanoDecompiler C++ Engine Integration
In `resources/engine_cpp/src/cfg.cpp`:
- `CFG::build()` scans bytecode leaders, segments blocks, and establishes bidirectional adjacency lists (`preds`, `succs`).
- Exception edges are segregated into protected regions to prevent cycle pollution in standard dominator algorithms.

## 5. References
- Aho, A. V., Lam, M. S., Sethi, R., & Ullman, J. D. *Compilers: Principles, Techniques, and Tools (2nd Edition)*. Addison-Wesley, 2006.
"""
    },
    {
        "file": "023_dominator_trees_and_post_dominance.md",
        "title": "Dominator Trees, Post-Dominance, and the Lengauer-Tarjan Algorithm",
        "num": "023",
        "content": """# Article 023: Dominator Trees, Post-Dominance, and the Lengauer-Tarjan Algorithm

## 1. Executive Summary & Formal Definitions
Dominance analysis is the cornerstone of control flow structuring:
- **Dominance**: A node $d$ dominates node $n$ ($d \text{ dom } n$) if every path from entry node $r$ to $n$ must pass through $d$.
- **Strict Dominance**: $d \text{ sdom } n \iff d \text{ dom } n \land d \neq n$.
- **Immediate Dominator ($\text{idom}(n)$)**: The unique strict dominator of $n$ that does not dominate any other strict dominator of $n$. The set of all immediate dominator edges forms the **Dominator Tree**.
- **Post-Dominance**: Node $p$ post-dominates $n$ ($p \text{ pdom } n$) if every path from $n$ to the exit node must pass through $p$. $\text{ipdom}(n)$ represents the convergence or join point of branches originating at $n$.

## 2. Lengauer-Tarjan Algorithm
Computes dominator trees in near-linear time $O(|E| \cdot \alpha(|E|, |V|))$ using depth-first search numbering and semi-dominators:
1. DFS traversal assigns discovery numbers `dfnum(v)`.
2. Compute semi-dominators using path-compression with disjoint sets (Union-Find).
3. Compute immediate dominators $\text{idom}(v)$ from semi-dominator links.

## 3. Role in AST Structuring
- If a conditional branch occurs at block $B$, the join point of the two branches is precisely $\text{ipdom}(B)$.
- All blocks post-dominated by $B$'s branch targets that precede $\text{ipdom}(B)$ form the `then` and `else` statement bodies.

## 4. NanoDecompiler C++ Engine Integration
In `resources/engine_cpp/src/structure.cpp`:
- `compute_dominators()` and `compute_post_dominators()` calculate immediate dominator relations used to delineate branch and loop nesting scopes.

## 5. References
- Lengauer, T., & Tarjan, R. E. *A fast algorithm for finding dominators in a flowgraph*. ACM TOPLAS, 1979.
"""
    },
    {
        "file": "024_loop_detection_and_natural_loops.md",
        "title": "Loop Detection, Natural Loops, and Header Identification",
        "num": "024",
        "content": """# Article 024: Loop Detection, Natural Loops, and Header Identification

## 1. Executive Summary & Formal Definitions
A **Loop** in a CFG is a subgraph that is strongly connected (every node in the loop can reach every other node in the loop) with a single entry point called the **Header**.
- **Back-Edge**: A directed edge $n \to h$ where $h \text{ dom } n$.
- **Natural Loop**: Given a back-edge $n \to h$, the natural loop of $n \to h$ is defined as:
$$\text{Loop}(n \to h) = \{ d \in V \mid d \text{ can reach } n \text{ without passing through } h \} \cup \{ h \}$$

## 2. Loop Nesting & Disjointness Properties
1. Any two natural loops are either:
   - Disjoint (share no nodes except perhaps an exit target).
   - Nested (one loop is entirely contained within the other).
   - Sharing the same header (loops with multiple latching back-edges).
2. The decompiler processes loops from innermost to outermost, collapsing recognized inner loops into abstract loop compound statements before structuring outer loops.

## 3. Loop Classification for Java
- **Pre-test Loop (`while`)**: Condition is checked at header $h$. If false, exits loop.
- **Post-test Loop (`do-while`)**: Body executes unconditionally first; condition is evaluated at latch block $n$.
- **Endless Loop (`while (true)`)**: Loop with no natural conditional exit edge; exited solely via `break`, `return`, or `throw`.

## 4. NanoDecompiler C++ Engine Integration
In `resources/engine_cpp/src/structure.cpp`:
- Detects back-edges via dominance check `dom.is_dom(h, n)`.
- Reconstructs loop scopes and distinguishes `while` from `do-while` based on condition block PC.

## 5. References
- Tarjan, R. E. *Testing flow graph reducibility*. Journal of Computer and System Sciences, 1974.
"""
    },
    {
        "file": "025_relooper_algorithm_and_extensions.md",
        "title": "The Relooper Algorithm: WebAssembly Origins and Java CFG Structuring",
        "num": "025",
        "content": """# Article 025: The Relooper Algorithm: WebAssembly Origins and Java CFG Structuring

## 1. Executive Summary & Context
Originally designed by Alon Zakai for Emscripten (LLVM to JavaScript/WebAssembly), the **Relooper Algorithm** reconstructs high-level structured control flow from arbitrary irreducible or reducible CFGs without relying on expensive backtracking.

## 2. The Three Core Structural Shapes
1. **Simple Shape**: A single basic block that transitions directly to at most one follow-up shape.
```
[ Block A ] ───► [ Follow Shape ]
```
2. **Loop Shape**: An entry block with a set of reachable recursive blocks and an exit shape:
```
┌──► [ Loop Body ] ───┐
│          │          │
└──────────┴──────────┘
           │
           ▼
     [ Exit Shape ]
```
3. **Multiple Shape**: A branching node that can jump to multiple independent shapes, structured as an `if/else` cascade or a switch block.

## 3. Extending Relooper for Java Decompilation
While Relooper in WebAssembly generates `loop` and `block` labels with break-to-label instructions, Java decompiler adaptations:
- Synthesize labeled `break <label>;` and `continue <label>;` when jumps cross multiple nesting levels.
- Re-order branching targets to prefer clean `if (cond) { ... } else { ... }` without artificial labels.

## 4. NanoDecompiler C++ Engine Integration
In `resources/engine_cpp/src/structure.cpp`:
- `Structurer::region()` adopts Relooper-style recursive region decomposition, isolating subgraphs into `BlockStmtNode`, `IfStmtNode`, and `WhileStmtNode`.

## 5. References
- Zakai, A. *Emscripten: an LLVM-to-JavaScript compiler*. ACM SPLASH, 2011.
"""
    },
    {
        "file": "026_interval_analysis_and_t1_t2_transformations.md",
        "title": "Interval Analysis, T1-T2 Transformations, and Limit Flow Graphs",
        "num": "026",
        "content": """# Article 026: Interval Analysis, T1-T2 Transformations, and Limit Flow Graphs

## 1. Executive Summary & Formal Theory
Cocke and Allen introduced **Interval Analysis** to partition a control flow graph into maximal single-entry subgraphs called **Intervals**.
An interval $I(h)$ with header $h$ satisfies:
1. $h$ is the only entry point into $I(h)$ from nodes outside $I(h)$.
2. All cycles inside $I(h)$ must contain $h$.

## 2. Hecht and Ullman T1-T2 Graph Transformations
Any reducible CFG can be collapsed into a single vertex through iterative application of two transformations:
- **T1 Transformation (Self-Loop Removal)**: If edge $n \to n$ exists, delete it and record a loop operation.
- **T2 Transformation (Predecessor Collapse)**: If node $n$ has a unique predecessor $m$, and $n \neq m$, and $m$ is not the entry node of another interval, merge $n$ into $m$.

## 3. Limit Flow Graph & Reducibility Criteria
A graph is **reducible** if and only if repeated application of T1 and T2 reduces the graph to a single node (the Limit Flow Graph).
If reduction halts with multiple nodes and no further T1 or T2 is applicable, the remaining subgraph is **irreducible** and contains multi-entry cycles.

## 4. Decompiler Application
Intervals provide natural encapsulation boundaries: each interval $I(h)$ corresponds directly to a Java structured compound statement (loop or nested block).

## 5. References
- Allen, F. E., & Cocke, J. *A program data flow analysis procedure*. Communications of the ACM, 1976.
- Hecht, M. S., & Ullman, J. D. *Characterizations of reducible flow graphs*. Journal of the ACM, 1974.
"""
    },
    {
        "file": "027_irreducible_control_flow_graphs.md",
        "title": "Irreducible Control Flow Graphs: Node Splitting and State Variable Emulation",
        "num": "027",
        "content": """# Article 027: Irreducible Control Flow Graphs: Node Splitting and State Variable Emulation

## 1. Executive Summary & Problem Formulation
An **Irreducible CFG** contains a cycle with multiple distinct entry nodes from outside the cycle. Java has no `goto` statement (it is a reserved keyword without syntax), meaning irreducible bytecode cannot be represented in standard structured Java without semantic transformation.

## 2. Resolution Technique 1: Node Splitting (Duplication)
Duplicate one of the entry nodes so each cycle entrance has its own private copy:
```
Before Splitting (Irreducible):
  Entry1 ──► [ LoopNode A ] ◄── Entry2
                  │
                  ▼
             [ LoopNode B ] ───► LoopNode A

After Node Splitting (Reducible):
  Entry1 ──► [ LoopNode A1 ] ──► [ LoopNode B1 ] ──► LoopNode A1
  Entry2 ──► [ LoopNode A2 ] ──► [ LoopNode B2 ] ──► LoopNode A2
```
*Advantage*: Generates clean Java without synthetic state variables.
*Disadvantage*: Exponential code size explosion if nested irreducible cycles exist.

## 3. Resolution Technique 2: State Variable Dispatcher (Flattening)
Introduce a synthetic integer variable `int __state = initial;` wrapped in a `while (true) switch (__state)` loop. Each basic block ends with an assignment to `__state` and `break;`.
*Advantage*: Guaranteed $O(|V|)$ transformation of any arbitrary graph.

## 4. NanoDecompiler C++ Engine Integration
In `resources/engine_cpp/src/structure.cpp`:
- Detects irreducible cross-links in `Structurer::region`.
- Emits annotated loop-with-comment or structured state jumps instead of aborting decompilation.

## 5. References
- Cifuentes, C., & Gough, K. J. *Decompilation of binary programs*. Software: Practice and Experience, 1995.
"""
    },
    {
        "file": "028_structuring_if_then_and_if_then_else.md",
        "title": "Structuring If-Then and If-Then-Else Conditional Branches",
        "num": "028",
        "content": """# Article 028: Structuring If-Then and If-Then-Else Conditional Branches

## 1. Executive Summary & Specification
In bytecode, a high-level `if (cond) { thenBlock } else { elseBlock }` is lowered into:
```
    [ Condition Eval ] ───► false branch jumps to ElseLabel
    [ Then Block ]
    goto JoinLabel
ElseLabel:
    [ Else Block ]
JoinLabel:
    [ Successor Block ]
```

## 2. Structuring Algorithm
1. Let $B$ be a block terminating with a conditional jump to $B_{target}$ with fallthrough to $B_{fall}$.
2. Compute $J = \text{ipdom}(B)$ (the immediate post-dominator).
3. If $B_{target} == J$:
   - This is an **`if-then` without else**: The then-clause is the subgraph rooted at $B_{fall}$ terminating at $J$.
4. If $B_{fall} == J$:
   - This is an **`if-then` with inverted condition**: Invert branch condition, then-clause is rooted at $B_{target}$.
5. If neither target equals $J$:
   - This is an **`if-then-else`**:
     - `then` body: Nodes reachable from $B_{fall}$ stopping at $J$.
     - `else` body: Nodes reachable from $B_{target}$ stopping at $J$.

## 3. Empty Else Optimization
If the `else` branch contains only a `goto` or returns immediately, restructure to avoid nested `else` indentation.

## 4. NanoDecompiler C++ Engine Integration
In `resources/engine_cpp/src/structure.cpp`:
- `Structurer::region()` recognizes conditional branch patterns and synthesizes `IfStmtNode` with attached `then_block` and optional `else_block`.

## 5. References
- Baker, B. S. *An algorithm for structuring flowgraphs*. Journal of the ACM, 1977.
"""
    },
    {
        "file": "029_structuring_short_circuit_boolean_expressions.md",
        "title": "Structuring Short-Circuit Boolean Expressions (&&, ||) and Condition Trees",
        "num": "029",
        "content": """# Article 029: Structuring Short-Circuit Boolean Expressions (&&, ||) and Condition Trees

## 1. Executive Summary & Specification
Java mandates short-circuit evaluation for logical AND (`&&`) and logical OR (`||`):
- `A && B`: If $A$ is false, $B$ is not evaluated.
- `A || B`: If $A$ is true, $B$ is not evaluated.
Compilers emit this as a cascade of individual conditional branch instructions (`ifeq`, `ifne`, etc.).

## 2. CFG Pattern Matching for Compound Conditions
- **Logical AND (`&&`) Pattern**:
  - Block $A$ jumps to `FalseTarget` if false; falls through to Block $B$.
  - Block $B$ jumps to `FalseTarget` if false; falls through to `TrueTarget`.
  - $\implies$ Collapse into: `if (A && B) goto TrueTarget; else goto FalseTarget;`.
- **Logical OR (`||`) Pattern**:
  - Block $A$ jumps to `TrueTarget` if true; falls through to Block $B$.
  - Block $B$ jumps to `TrueTarget` if true; falls through to `FalseTarget`.
  - $\implies$ Collapse into: `if (A || B) goto TrueTarget; else goto FalseTarget;`.

## 3. Normalization via De Morgan's Laws
$$\neg(A \land B) \equiv (\neg A \lor \neg B), \quad \neg(A \lor B) \equiv (\neg A \land \neg B)$$
Decompilers apply De Morgan's laws to eliminate unnecessary negations, ensuring expressions like `if (!(a == 0 && b == 0))` are emitted cleanly as `if (a != 0 || b != 0)`.

## 4. NanoDecompiler C++ Engine Integration
In `resources/engine_cpp/src/structure.cpp` and `stackvm.cpp`:
- Merges sequential single-condition blocks that share common exit targets into compound `BinaryExpr(OP_LOGICAL_AND)` and `BinaryExpr(OP_LOGICAL_OR)`.

## 5. References
- JLS §15.23, §15.24: Conditional-And Operator `&&`, Conditional-Or Operator `||`.
"""
    },
    {
        "file": "030_loop_structuring_while_do_while_for.md",
        "title": "Loop Structuring: while, do-while, and for Loop Recovery",
        "num": "030",
        "content": """# Article 030: Loop Structuring: while, do-while, and for Loop Recovery

## 1. Executive Summary & Loop Classification
Bytecode uses identical conditional jumps (`if_icmp*`) for `while`, `do-while`, and `for` loops. The decompiler determines the intended loop flavor by analyzing the location of the loop test and induction variables.

## 2. Loop Form Identification
1. **`while (cond)` Loop**:
   - Condition check is at the loop header $h$.
   - False edge exits the loop ($h \to \text{exit}$).
   - True edge leads to loop body, which ends with an unconditional `goto h`.
2. **`do { ... } while (cond)` Loop**:
   - Loop header $h$ is an unconditional statement block.
   - Loop latch block evaluates condition: true edge jumps back to $h$; false edge falls through to exit.
3. **`for (init; cond; step)` Loop**:
   - Predecessor block of $h$ contains an assignment to variable $i$ (`init`).
   - Latch block contains an increment/update of $i$ (`step`), e.g., `iinc` or `i = i + 1`.
   - Variable $i$ is not modified elsewhere in the loop body.
   - $\implies$ Emitted cleanly as standard `for (int i = 0; i < N; i++)`.

## 3. Infinite Loops (`while (true)`)
If the loop subgraph has no natural back-edge condition (all exits occur via internal `break`, `return`, or `throw`), emit as `while (true) { ... }`.

## 4. NanoDecompiler C++ Engine Integration
In `resources/engine_cpp/src/structure.cpp`:
- Distinguishes header-test loops (`WhileStmtNode`) from latch-test loops (`DoWhileStmtNode`).
- Inspects induction variables to reconstruct concise `for` loops.

## 5. References
- Muchnick, S. S. *Advanced Compiler Design and Implementation*. Chapter 18: Control-Flow Optimizations.
"""
    },
    {
        "file": "031_break_and_continue_resolution.md",
        "title": "Labeled break and continue Target Resolution in Nested Constructs",
        "num": "031",
        "content": """# Article 031: Labeled break and continue Target Resolution in Nested Constructs

## 1. Executive Summary & Specification
Java supports unlabeled and labeled control transfers:
- `break`: Exits the immediately enclosing `switch`, `while`, `do`, or `for`.
- `continue`: Skips remainder of the current iteration of the immediately enclosing loop.
- `break <label>` / `continue <label>`: Exits or continues the specific enclosing construct flagged with `<label>:`.

## 2. Target Resolution Algorithm
When a jump edge $B \to T$ is encountered inside a structured loop or switch:
1. If $T$ is the loop header $h$ of the immediately enclosing loop $\implies$ emit **`continue;`**.
2. If $T$ is the loop exit block of the immediately enclosing loop $\implies$ emit **`break;`**.
3. If $T$ is the header of an outer loop enclosing the current loop $\implies$ synthesize label on outer loop and emit **`continue outerLabel;`**.
4. If $T$ is the exit block of an outer loop or block $\implies$ synthesize label and emit **`break outerLabel;`**.

## 3. Eliminating Unnecessary Labels
Labels add visual noise. The decompiler must maintain a stack of active lexical scopes and only emit a label if an explicit jump requires disambiguation.

## 4. NanoDecompiler C++ Engine Integration
In `resources/engine_cpp/src/structure.cpp`:
- Resolves jump targets against lexical loop stacks.
- Emits `BreakStmtNode` and `ContinueStmtNode` with optional label identifiers.

## 5. References
- JLS §14.15: The `break` Statement.
- JLS §14.16: The `continue` Statement.
"""
    },
    {
        "file": "032_switch_statement_reconstruction.md",
        "title": "Switch Statement Reconstruction: tableswitch vs lookupswitch",
        "num": "032",
        "content": """# Article 032: Switch Statement Reconstruction: tableswitch vs lookupswitch

## 1. Executive Summary & Bytecode Mechanics
The JVM provides two specialized multi-way branch bytecodes (JVMS §6.5):
1. **`tableswitch` (0xAA)**:
   - Used for dense case keys.
   - Binary format contains `default_offset`, `low_byte`, `high_byte`, and a direct jump table indexed by $(key - low)$.
   - Execution is $O(1)$ direct array index lookup.
2. **`lookupswitch` (0xAB)**:
   - Used for sparse case keys.
   - Binary format contains `default_offset`, `npairs`, followed by sorted pairs of `(int32_key, int32_offset)`.
   - Execution is $O(\log N)$ binary search.

## 2. High-Level Switch Recovery
Both opcodes are translated into a single unified `SwitchStmtNode`:
1. Group cases that share identical target block offsets into multi-case labels (`case 1: case 2: ...`).
2. Identify the `default:` target block.
3. Detect case **fall-through**: If case $i$ does not end with a jump to switch exit, return, or throw, retain fall-through semantics; otherwise append `break;`.

## 3. Switch Expressions (Java 14+)
Modern Java supports switch expressions with arrow syntax:
```java
int result = switch (status) {
    case 1 -> 100;
    case 2 -> 200;
    default -> throw new IllegalStateException();
};
```
Decompilers detect when every case block yields a value to the same stack destination and format the switch as a concise expression.

## 4. NanoDecompiler C++ Engine Integration
In `resources/engine_cpp/src/structure.cpp` and `switchmap.cpp`:
- Translates `tableswitch` and `lookupswitch` into structured `SwitchStmtNode`.
- Tracks default target and resolves jump exits cleanly.

## 5. References
- JVMS §6.5: `tableswitch`, `lookupswitch`.
- JEP 361: *Switch Expressions*. OpenJDK, 2020.
"""
    },
    {
        "file": "033_structuring_exception_handlers.md",
        "title": "Structuring Exception Handlers, Protected Ranges, and Multi-Catch Blocks",
        "num": "033",
        "content": """# Article 033: Structuring Exception Handlers, Protected Ranges, and Multi-Catch Blocks

## 1. Executive Summary & Specification
In Java, exception handling is structured hierarchically (`try { ... } catch (E e) { ... }`). In bytecode, it is represented as flat rows in the exception table with half-open intervals $[start, end)$ targeting `handler_pc`.

## 2. Structuring Algorithm
1. **Interval Clustering**: Group exception table rows that share identical $[start, end)$ ranges. These form the individual `catch` clauses of a single `try` statement.
2. **Range Containment Hierarchy**: Construct a containment tree of ranges:
   - Range $A$ contains Range $B$ if $start_A \le start_B$ and $end_B \le end_A$.
   - Process ranges from innermost to outermost.
3. **Multi-Catch Reconstruction (Java 7+)**:
   - If multiple rows with the same $[start, end)$ point to the exact same `handler_pc`, combine their exception types into a multi-catch clause:
   ```java
   catch (IOException | SQLException e) { ... }
   ```

## 3. Exception Variable Scope
At entry to `handler_pc`, the JVM pushes the thrown exception object onto the operand stack. The first instruction of the handler is almost universally `astore <var>`, binding the exception to a local variable.

## 4. NanoDecompiler C++ Engine Integration
In `resources/engine_cpp/src/structure.cpp` and `catchclean.cpp`:
- `build_try()` organizes ranges into clean `TryCatchRegion` hierarchies.
- Binds handler stack item to caught exception variable.

## 5. References
- JLS §14.20: The `try` statement.
- JVMS §4.7.3: Exception Tables.
"""
    },
    {
        "file": "034_finally_block_reconstruction.md",
        "title": "Finally Block Reconstruction and Duplicate Bytecode De-duplication",
        "num": "034",
        "content": """# Article 034: Finally Block Reconstruction and Duplicate Bytecode De-duplication

## 1. Executive Summary & Compiler Generation Patterns
Since the deprecation of `jsr`/`ret`, Java compilers implement `finally` blocks through **code duplication**:
1. A copy of the finally block body is inserted before every normal exit point (every `return`, `break`, or `continue`) inside the `try` and `catch` blocks.
2. An all-encompassing exception handler (`catch_type == 0`, covering both the try block and all catch blocks) is generated. This handler executes another copy of the finally block and then re-throws the exception via `athrow`.

## 2. Decompilation Reconstruction Algorithm
If a decompiler outputs raw bytecode without recognizing this pattern, the finally code will appear duplicated 3 to 10 times in every method exit!
- **Algorithm**:
  1. Identify any `catch_type == 0` handler that terminates in `athrow`.
  2. Extract the statement sequence immediately preceding `athrow` as the candidate `finally` body $F$.
  3. Scan preceding normal exit paths: if a sequence isomorphic to $F$ precedes returns/exits from the try/catch blocks, prune that sequence from the AST.
  4. Emit $F$ exactly once inside the `finally { ... }` block.

## 3. NanoDecompiler C++ Engine Integration
In `resources/engine_cpp/src/catchclean.cpp`:
- `CatchClean::clean_handlers()` detects duplicated finally blocks, strips repetitive exit code, and consolidates them into a single `finally` clause.

## 4. References
- Gosling, J., et al. *The Java Language Specification*. §14.20.2: Execution of `try-finally` and `try-catch-finally`.
"""
    },
    {
        "file": "035_synchronized_blocks_and_monitors.md",
        "title": "Synchronized Blocks, Monitor Invariants, and Synthetic Handlers",
        "num": "035",
        "content": """# Article 035: Synchronized Blocks, Monitor Invariants, and Synthetic Handlers

## 1. Executive Summary & Specification
Java supports mutual exclusion at method level (`ACC_SYNCHRONIZED`) and block level (`synchronized (expr) { ... }`).
Block-level synchronization is compiled using `monitorenter` (0xC2) and `monitorexit` (0xC3) bytecodes (JVMS §6.5).

## 2. Invariant Rules & Compiler Pattern
The JVM requires that for every execution path exiting the synchronized block (normal completion, return, or exception), `monitorexit` must be executed exactly once on the lock object.
Compiler sequence:
```
    aload_lock
    dup
    astore_lock_temp
    monitorenter
TryStart:
    [ Synchronized Body ]
    aload_lock_temp
    monitorexit
    goto EndLabel
ExceptionHandler: (covers TryStart to EndLabel, catch_type = 0)
    aload_lock_temp
    monitorexit
    athrow
EndLabel:
```

## 3. Decompiler Recovery Strategy
1. Identify `monitorenter` instruction and extract the lock expression.
2. Locate the synthetic exception handler covering the block that executes `monitorexit` and `athrow`.
3. Eliminate the synthetic temporary lock variable, the duplicate `monitorexit` calls, and the synthetic exception handler.
4. Wrap the protected body in `synchronized (lockExpr) { ... }`.

## 4. NanoDecompiler C++ Engine Integration
In `resources/engine_cpp/src/catchclean.cpp` and `structure.cpp`:
- Identifies monitor enter/exit pairs and converts them into structured `SynchronizedStmtNode`.

## 5. References
- JVMS §3.14: Synchronization.
- JLS §14.19: The `synchronized` Statement.
"""
    },
    {
        "file": "036_unreachable_and_dead_code_elimination.md",
        "title": "Unreachable and Dead Code Elimination in Decompiler AST",
        "num": "036",
        "content": """# Article 036: Unreachable and Dead Code Elimination in Decompiler AST

## 1. Executive Summary & Specification
Bytecode often contains dead or unreachable code due to:
- Constant folding at compile time (e.g. `if (DEBUG) { ... }` where `static final boolean DEBUG = false;`).
- Obfuscators injecting unreachable instructions to confuse analyzers.
- Compiler optimizations leaving abandoned blocks.

## 2. Reachability Analysis
1. Perform Depth-First Search (DFS) starting from the entry basic block ($PC = 0$).
2. Follow all direct jump, branch, switch, and valid exception edges.
3. Any basic block not reached during the traversal is strictly **unreachable dead code**.
4. In AST generation, unreachable blocks must be pruned unless they contain synthetic debugging markers or decompilation fallback hints.

## 3. Safe Fallback Guarantee
In adversarial or obfuscated binaries, an apparently unreachable block may be reached via dynamic reflection or corrupted jump targets. Rather than crashing:
- NanoDecompiler appends unconsumed blocks safely to the AST sequence with diagnostic annotations, avoiding decompiler aborts.

## 4. NanoDecompiler C++ Engine Integration
In `resources/engine_cpp/src/structure.cpp`:
- `check_full_coverage()` ensures all CFG blocks are accounted for.
- `recover_unconsumed_blocks()` appends detached blocks safely without aborting decompilation.

## 5. References
- Cooper, K. D., & Torczon, L. *Engineering a Compiler (2nd Edition)*. Morgan Kaufmann, 2011.
"""
    },
    {
        "file": "037_ast_representation_for_decompilers.md",
        "title": "Abstract Syntax Tree (AST) Hierarchy for Decompilers",
        "num": "037",
        "content": """# Article 037: Abstract Syntax Tree (AST) Hierarchy for Decompilers

## 1. Executive Summary & Node Taxonomy
The decompiler AST represents the structured semantic hierarchy of the program. It bifurcates strictly into **Statements** and **Expressions**.

```
                         [ AstNode ]
                         /         \\
                [ AstStmt ]       [ AstExpr ]
                 /   |   \\          /    |    \\
            Block   If   Loop    Binary Unary Call
```

## 2. Core Statement Node Hierarchy
- `BlockStmtNode`: Ordered list of child statements `{ S1; S2; ... }`.
- `IfStmtNode`: Condition expression, `then` block, optional `else` block.
- `WhileStmtNode`, `DoWhileStmtNode`, `ForStmtNode`: Loop constructs with conditions and step statements.
- `SwitchStmtNode`: Selector expression, case entries with associated blocks.
- `TryCatchStmtNode`: Protected block, catch clauses with caught exception types, optional finally block.
- `ReturnStmtNode`: Optional return expression.
- `ThrowStmtNode`: Thrown exception expression.
- `ExprStmtNode`: Wrapper for expressions with side effects (method invocations, assignments).

## 3. Core Expression Node Hierarchy
- `VarExpr`: Local variable or parameter reference.
- `LiteralExpr`: Integer, float, string, class, null literals.
- `BinaryExpr`: Arithmetic, bitwise, comparison, logical operators.
- `UnaryExpr`: Negation, bitwise NOT, logical NOT, cast expressions.
- `CallExpr`: Method call with receiver, method name, argument list.
- `NewExpr`: Object instantiation (`new Foo(...)`).
- `ArrayAccessExpr`, `FieldAccessExpr`.

## 4. NanoDecompiler C++ Engine Integration
In `resources/engine_cpp/include/ast_nodes.hpp`:
- Comprehensive C++ polymorphic class hierarchy with visitor support and clean memory management.

## 5. References
- Jones, N. D. *Abstract Syntax Trees in Compiler Construction*. ACM Computing Surveys, 2003.
"""
    },
    {
        "file": "038_ast_simplification_and_canonicalization.md",
        "title": "AST Simplification, Canonicalization Passes, and Redundant Cast Elimination",
        "num": "038",
        "content": """# Article 038: AST Simplification, Canonicalization Passes, and Redundant Cast Elimination

## 1. Executive Summary & Purpose
Raw ASTs synthesized from bytecode often contain unnatural compiler artifacts:
- Redundant parenthesis and nested singleton blocks `{{ S; }}`.
- Unnecessary primitive casts (e.g. `(int) (x + y)` where operands are already ints).
- Identity arithmetic operations (`x + 0`, `x * 1`, `x & -1`).
- Double negations (`!(!x)` $\to x$).

## 2. Canonicalization Passes
1. **Block Flattening**: If a block contains an inner child block that declares no conflicting local variable scopes, splice child statements directly into the parent block.
2. **Redundant Cast Stripping**:
   - Inspect receiver and parameter types: if the static type of the operand already satisfies the method signature or target variable type, remove `checkcast` / primitive cast node.
3. **Boolean Condition Inversion**: If an `if-then-else` statement has an empty `then` block and a populated `else` block, invert the condition and swap the blocks.

## 3. NanoDecompiler C++ Engine Integration
In `resources/engine_cpp/src/engine.cpp` and `emit.cpp`:
- Post-processing AST rewrite passes canonicalize expressions prior to Java code emission.

## 4. References
- Muchnick, S. S. *Advanced Compiler Design and Implementation*. Chapter 12: AST Transformations.
"""
    },
    {
        "file": "039_control_flow_flattening_recovery.md",
        "title": "Control Flow Flattening Recovery and Dispatcher Loop Unflattening",
        "num": "039",
        "content": """# Article 039: Control Flow Flattening Recovery and Dispatcher Loop Unflattening

## 1. Executive Summary & Obfuscation Mechanism
**Control Flow Flattening** (introduced by Chenxi Wang, 2001) breaks apart normal structured control flow into disjoint basic blocks and encloses them all within a single dispatcher loop with a multi-way `switch` statement:
```
int state = 1;
while (state != 0) {
    switch (state) {
        case 1: [ Original Block A ]; state = 2; break;
        case 2: if (cond) state = 3; else state = 4; break;
        ...
    }
}
```
All hierarchical nesting (`if`, `while`, `try`) is destroyed, turning the CFG into a flat star-shaped graph.

## 2. Unflattening Recovery Algorithm
1. **Dispatcher Identification**: Locate `while` loop whose header directly dominates a single `switch` statement indexed by a state variable $S$.
2. **Symbolic State Evaluation**: For each switch case $C_i$:
   - Trace assignments to state variable $S$ along each exit path of $C_i$.
   - Compute transition tuples: $(C_i \to C_j)$ for unconditional transitions, or $(C_i \to C_j \text{ if } cond \text{ else } C_k)$ for conditional transitions.
3. **CFG Reconstruction**: Rebuild genuine CFG edges directly between the recovered basic blocks, completely removing the dispatcher loop and state variable.
4. Apply standard structurer to the recovered CFG.

## 3. NanoDecompiler C++ Engine Integration
In `resources/engine_cpp/src/structure.cpp` and `switchmap.cpp`:
- Recognizes dispatcher loops and resolves state transitions.

## 4. References
- Wang, C., et al. *Reverse Engineering of Flattened Control Flow*. IEEE Software Engineering, 2001.
- Udupa, S. K., Debray, S. K., & Matias, M. *Deobfuscation: Reverse Engineering Obfuscated Code*. USENIX Security, 2005.
"""
    },
    {
        "file": "040_decompiler_correctness_and_verification.md",
        "title": "Decompiler Correctness, Semantic Preservation, and Fuzzing Strategies",
        "num": "040",
        "content": """# Article 040: Decompiler Correctness, Semantic Preservation, and Fuzzing Strategies

## 1. Executive Summary & Verification Criteria
A decompiler is strictly **correct** if for every valid input class file $C$, decompiling $C$ into source $S$ followed by recompiling $S$ with standard `javac` produces a binary $C'$ that is **semantically equivalent** to $C$:
$$\forall C \in \text{ValidClassFiles}, \quad \text{Semantics}(\text{javac}(\text{Decompile}(C))) \equiv \text{Semantics}(C)$$

## 2. Differential Testing & Fuzzing Architecture
To guarantee engine stability across millions of edge cases:
1. **Round-Trip Testing**: Decompile JAR -> Recompile with `javac` -> Execute unit tests on recompiled classes.
2. **AST Invariant Fuzzing**: Mutate bytecode with arbitrary branch interleavings and verify decompiler never crashes, leaks memory, or emits invalid Java syntax.
3. **Differential Comparison**: Run multiple decompilers (NanoDecompiler, CFR, Fernflower, Procyon) against the same benchmark and compare decompiled AST branch structures.

## 3. NanoDecompiler C++ Engine Integration
In `resources/engine_cpp/src/verify.cpp`:
- Automated sanity checks on CFG coverage, stack balance, and local variable scoping prior to final code emission.

## 4. References
- Myreen, M. O. *Decompilation as Reasoning in Logic*. PhD Thesis, University of Cambridge, 2008.
- Holler, C., et al. *Fuzzing Compilers and Decompilers with Grammar-based Mutators*. USENIX Security, 2012.
"""
    }
]
